# Makefile for timelib-go with re2go integration

.PHONY: all build clean regenerate test

all: build

# Build the Go package
build: parse_date_gen.go parse_iso_intervals_gen.go
	go build .

# Regenerate parse_date_gen.go from parse_date_go.re using re2go
parse_date_gen.go: parse_date_go.re
	re2go --api custom -b parse_date_go.re --output parse_date_gen.go

# Regenerate parse_iso_intervals_gen.go from parse_iso_intervals_go.re using re2go
parse_iso_intervals_gen.go: parse_iso_intervals_go.re
	re2go --api custom -b parse_iso_intervals_go.re --output parse_iso_intervals_gen.go
	@# Rename YYMAXFILL to avoid conflict with parse_date_gen.go
	@sed -i 's/var YYMAXFILL int/var YYMAXFILL_ISO int/' parse_iso_intervals_gen.go

# Extract constants from C source (if needed)
parse_date_constants.go: parse_date_c.re
	@echo "Extracting constants from parse_date_c.re..."
	@echo "// Code generated from parse_date.re; DO NOT EDIT." > $@
	@echo "// To regenerate, run: make parse_date_constants.go" >> $@
	@echo "" >> $@
	@echo "package timelib" >> $@
	@echo "" >> $@
	@echo "// Token type constants extracted from parse_date.re" >> $@
	@echo "const (" >> $@
	@grep "^#define\s\+\(EOI\|TIME\|DATE\|TIMELIB_[A-Z_]*\)\s\+[0-9]" parse_date_c.re | \
		sed 's/#define\s\+\([A-Z_0-9]*\)\s\+\([0-9]*\).*/	\1 = \2/' >> $@
	@echo ")" >> $@

# Full regeneration from upstream C source
regenerate: parse_date_c.re parse_iso_intervals_c.re
	@echo "Copying latest parse_date.re from parent directory..."
	@if [ -f ../parse_date.re ]; then \
		cp ../parse_date.re parse_date_c.re; \
		echo "Updated parse_date_c.re"; \
	else \
		echo "Warning: ../parse_date.re not found"; \
	fi
	@echo "Copying latest parse_iso_intervals.re from parent directory..."
	@if [ -f ../parse_iso_intervals.re ]; then \
		cp ../parse_iso_intervals.re parse_iso_intervals_c.re; \
		echo "Updated parse_iso_intervals_c.re"; \
	else \
		echo "Warning: ../parse_iso_intervals.re not found"; \
	fi
	@echo "Regenerating parse_date_gen.go..."
	$(MAKE) parse_date_gen.go
	@echo "Regenerating parse_iso_intervals_gen.go..."
	$(MAKE) parse_iso_intervals_gen.go
	@echo "Done!"

# Run tests
test: build
	go test -v ./...

# Clean generated files
clean:
	rm -f parse_date_gen.go parse_iso_intervals_gen.go
	go clean

# Show statistics
stats:
	@echo "=== Source File Statistics ==="
	@echo "parse_date_c.re (C original):"
	@wc -l parse_date_c.re
	@echo ""
	@echo "parse_date_go.re (Go adaptation):"
	@wc -l parse_date_go.re
	@echo ""
	@echo "parse_date_gen.go (generated by re2go):"
	@wc -l parse_date_gen.go 2>/dev/null || echo "Not generated yet"
	@echo ""
	@echo "parse_date_constants.go (extracted constants):"
	@wc -l parse_date_constants.go

.PHONY: stats
